[tools]
swiftlint = "0.59.0"

[tasks]
lint = ["./Tools/format-check", "./Tools/check-packages"]
format = "./Tools/format"
test = "swift test"
test-integration = "xcodebuild test -scheme SnapshotsIntegrationTests -destination 'platform=iOS Simulator,name=iPhone 17'"
