#!/bin/zsh

set -e

root_dir="${0%/*}"/..


# Swiftformat

xcrun swift-format \
  lint $root_dir \
  -r \
  -p


# Swiftlint

swiftlint \
  --config "${root_dir}/.swiftlint.yml" \
  --progress \
  --strict \
  $root_dir
