#!/bin/zsh

set -e

root_dir="${0%/*}"/..


# Swiftformat

echo ""
echo "swift-format"

xcrun swift-format \
  format $root_dir \
  -r \
  -i \
  -p


# Swiftlint

echo ""
echo "swiftlint [autocorrecting if possible]"

swiftlint \
  --config "${root_dir}/.swiftlint.yml" \
  --strict \
  --progress \
  --fix \
  $root_dir

echo ""
echo "swiftlint [check remaining errors]"

swiftlint \
  --config "${root_dir}/.swiftlint.yml" \
  --progress \
  --strict \
  $root_dir
